### ISSUE TITLE
cool project, any updates?

### ISSUE THREAD

**Issue by mte0** [TricksterGuy/DiscordCryptoBot#1]
When are you planning on adding the paper trading feature etc? also some instructions on setting up (especially abt the slash commands) would be nice!

**Comment by TricksterGuy** [comment]
Uhh this is a work in progress type thing I have most of this stuff implemented in a very messy way and just cleaning up the code. 

That and the whole multiple discord python libraries out there and porting the code over to pycord last I checked.

I'd rather not just dump it all in the repo as its not clean or well tested. _I have standards_ for what I put up on github.
